#!/bin/bash

nums=""
while [ $(echo "$nums" | wc -w) -lt 5 ]; do
  n=$(shuf -i 1-50 -n 1)
  if ! echo "$nums" | grep -qw "$n"; then
    nums="$nums $n"
  fi
done

stars=""
while [ $(echo "$stars" | wc -w) -lt 2 ]; do
  s=$(shuf -i 1-12 -n 1)
  if ! echo "$stars" | grep -qw "$s"; then
    stars="$stars $s"
  fi
done

nums_sorted=$(echo $nums | tr ' ' '\n' | sort -n | paste -s -d',' | sed 's/,/, /g')
stars_sorted=$(echo $stars | tr ' ' '\n' | sort -n | paste -s -d',' | sed 's/,/, /g')

echo "Su EUROMILLONES es $nums_sorted – $stars_sorted"
